# Generated by Django 3.1.4 on 2020-12-02 17:31

from django.db import migrations, models
import django.db.models.deletion

"""
create table 'users_user'
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('monthly_limit', models.FloatField()),
                ('income_scope',  models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='commons.incomeranges')),
            ],
        ),
    ]
