# Generated by Django 3.1.4 on 2020-12-04 10:44

import django.core.validators
from django.db import migrations, models

"""
    - Alter field email on user: set unique
    - Alter field monthly_limit on user: not necessary
    - Alter field password on user: set min and max length
"""


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_limit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
