# Generated by Django 3.1.4 on 2020-12-04 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201204_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='income_scope',
            new_name='income_range',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
