# Generated by Django 3.1.4 on 2020-12-07 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201207_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 7, 18, 56, 0, 612595, tzinfo=utc)),
        ),
    ]
