# Generated by Django 3.1.4 on 2021-01-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201207_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_data_collection',
            field=models.BooleanField(default=False),
        ),
    ]
