# Generated by Django 3.1.4 on 2020-12-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_changed_table_names'),
        ('commons', '0002_inserting_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRanges',
            new_name='AgeRange',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='IncomeRanges',
            new_name='IncomeRange',
        ),
    ]
