# Generated by Django 3.1.4 on 2021-01-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0003_changed_table_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.incomerange')),
                ('age_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.agerange')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.category')),
                ('gender', models.CharField(max_length=1)),
                ('value', models.DecimalField(decimal_places=2, max_digits=19)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
