# Generated by Django 3.1.4 on 2021-01-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_changed_table_names'),
        ('stats', '0002_fill_stats_table_procedure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Stats',
        ),
    ]
